[package]
name = "huffman"
version = "0.1.0"
authors = ["sebastian_perez"]


[dependencies]
petgraph = "0.2.6"
bincode = "*"
serde = "*"

[lib]
name="huffman"
path="src/lib.rs"

[[bin]]
name="rip"
path="src/rip.rs"
